name: Terraform AKS Infrastructure

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Prepare Terraform variables
        working-directory: terraform
        env:
          TF_POSTGRES_ADMIN_PASSWORD: ${{ secrets.TF_POSTGRES_ADMIN_PASSWORD }}
        run: |
          cp terraform.tfvars.example terraform.tfvars
          printf '\npostgres_admin_password = "%s"\n' "$TF_POSTGRES_ADMIN_PASSWORD" >> terraform.tfvars
      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve